// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcC9JiaQiwrrbBe5QwhxFYIuJDsqzR7IQ',
    appId: '1:139692684881:web:b15f1820509407c52aea70',
    messagingSenderId: '139692684881',
    projectId: 'notes-app-assessment-1cdb3',
    authDomain: 'notes-app-assessment-1cdb3.firebaseapp.com',
    storageBucket: 'notes-app-assessment-1cdb3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiI-q_nB2l8mBPNTsGGAqctXOVdoZ0Guk',
    appId: '1:139692684881:android:b5b624fbfa9fb0b62aea70',
    messagingSenderId: '139692684881',
    projectId: 'notes-app-assessment-1cdb3',
    storageBucket: 'notes-app-assessment-1cdb3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUEDKYoZsLYJII_3I68iJmbzGIJnev-TQ',
    appId: '1:139692684881:ios:e33e2386dbe6e7312aea70',
    messagingSenderId: '139692684881',
    projectId: 'notes-app-assessment-1cdb3',
    storageBucket: 'notes-app-assessment-1cdb3.firebasestorage.app',
    iosBundleId: 'com.example.notesAppAssessment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUEDKYoZsLYJII_3I68iJmbzGIJnev-TQ',
    appId: '1:139692684881:ios:e33e2386dbe6e7312aea70',
    messagingSenderId: '139692684881',
    projectId: 'notes-app-assessment-1cdb3',
    storageBucket: 'notes-app-assessment-1cdb3.firebasestorage.app',
    iosBundleId: 'com.example.notesAppAssessment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcC9JiaQiwrrbBe5QwhxFYIuJDsqzR7IQ',
    appId: '1:139692684881:web:3811d7c91bc9d3cc2aea70',
    messagingSenderId: '139692684881',
    projectId: 'notes-app-assessment-1cdb3',
    authDomain: 'notes-app-assessment-1cdb3.firebaseapp.com',
    storageBucket: 'notes-app-assessment-1cdb3.firebasestorage.app',
  );
}
